##Application Name to appear in Azure App Insights
spring:
  application:
    name: deliveryMoment-crud-service
  ##Properties for Mongo
  data:
    mongodb:
#      database: deliverymoment-db
#      uri: mongodb://deliverymoment-cosmos-mongo-db:0LTdfL6WYtDKS4zINtXwkbUbt9UV4sZt0RA0KCqTgrn0qmXHWMQrgXmGQd7uYueYgClYYUaXjav8EzDCcty1xg==@deliverymoment-cosmos-mongo-db.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&maxIdleTimeMS=120000&appName=@deliverymoment-cosmos-mongo-db@
#      database:
#      uri:
server:
  port: 8080
  application:
    name: deliveryMoment-crud-service
##Properties for Prometheus End Points
endpoints:
  prometheus:
    enabled: true
management:
  endpoints:
    web:
      base-path: "/servicetemplate/api/v1/service-template"
      exposure:
        include: "*"
##OpenAPI To Enable
springdoc:
  swagger-ui.path: "/servicetemplate/api/v1/service-template/swagger-ui-custom.html"
  api-docs.path: "/servicetemplate/api/v1/store-cluster-service/api-docs"
##Azure Cosmos Credentials and App Insights Key
azure:
  application-insights:
    instrumentation-key: f0807cb4-14fe-437c-ab41-6ed885735d2b

service:
  perf-urls:
    get-model-url: "http://localhost:8097/servicetemplate/api/v1/getModel"
  test-data:
    id: "1"
